# Part II: Data Manipulation and Analysis (Pandas)

This section performs statistical analysis and data manipulation using Pandas.

In [18]:
import numpy as np
import pandas as pd

## Step 1: Display First 5 Rows and Summary Statistics

The first 5 rows and statistical summary of the dataset are displayed for analysis.

In [19]:
print(df.head())

     Electronics  Clothing  Home & Kitchen  Sports  Total Sales  Growth Rate
Jan       4472.1   3216.40            4390    4796        17939          NaN
Feb       3819.6   3559.80            1590    1711        11733   -34.595016
Mar       2812.5   3627.80            4711    4697        16801    43.194409
Apr       2205.9   2930.80            4771    2994        13664   -18.671508
May       4236.3   2593.35            1095    1889        10742   -21.384660


In [20]:
print(df.describe())

       Electronics     Clothing  Home & Kitchen       Sports   Total Sales  \
count    12.000000    12.000000       12.000000    12.000000     12.000000   
mean   3190.200000  2961.754167     3309.500000  3224.250000  13562.833333   
std     818.478475   873.192616     1467.358883  1264.542255   2277.586914   
min    2178.900000  1298.800000     1095.000000  1241.000000  10742.000000   
25%    2571.975000  2478.600000     1798.500000  2237.000000  11919.750000   
50%    2959.650000  3253.800000     3551.000000  3307.000000  13228.000000   
75%    3849.300000  3550.875000     4726.000000  4327.250000  14546.000000   
max    4472.100000  4222.800000     4972.000000  4796.000000  17939.000000   

       Growth Rate  
count    11.000000  
mean      1.656638  
std      25.741527  
min     -34.595016  
25%     -20.028084  
50%       3.020053  
75%      19.874048  
max      43.194409  


## Step 2: Calculate Total Sales

Total sales are calculated:
- Category-wise
- Month-wise

In [21]:
category_total = df.sum()

print(category_total)

Electronics        38282.400000
Clothing           35541.050000
Home & Kitchen     39714.000000
Sports             38691.000000
Total Sales       162754.000000
Growth Rate           18.223013
dtype: float64


In [22]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    34813.500000
Feb    22378.804984
Mar    32692.494409
Apr    26547.028492
May    20534.265340
Jun    27266.137349
Jul    23411.414367
Aug    27462.336588
Sep    20880.012378
Oct    23961.147546
Nov    25012.620053
Dec    30040.911507
dtype: float64


## Step 3: Average Sales Growth

Percentage growth between consecutive months is calculated for each category.

In [23]:
growth = df.pct_change()

print(growth)

     Electronics  Clothing  Home & Kitchen    Sports  Total Sales  Growth Rate
Jan          NaN       NaN             NaN       NaN          NaN          NaN
Feb    -0.145905  0.106765       -0.637813 -0.643244    -0.345950          NaN
Mar    -0.263666  0.019102        1.962893  1.745178     0.431944    -2.248573
Apr    -0.215680 -0.192127        0.012736 -0.362572    -0.186715    -1.432267
May     0.920441 -0.115139       -0.770488 -0.369071    -0.213847     0.145310
Jun    -0.102401  0.269092        0.660274  1.225516     0.314373    -2.470089
Jul    -0.426982 -0.491477        1.734873 -0.376784    -0.151356    -1.481454
Aug     0.194961  1.523108       -0.190467 -0.101908     0.188366    -2.244519
Sep     0.512617 -0.494565       -0.321491 -0.472588    -0.237376    -2.260187
Oct    -0.361517  0.613700       -0.362871  2.087027     0.143475    -1.604422
Nov     0.235505 -0.622902        0.768391  0.235970     0.030201    -0.789507
Dec    -0.165991  1.731675        0.558011 -0.235480

In [24]:
avg_growth = growth.mean()

print(avg_growth)

Electronics       0.016489
Clothing          0.213385
Home & Kitchen    0.310368
Sports            0.248367
Total Sales       0.016566
Growth Rate      -0.846149
dtype: float64


## Step 4: Add New Columns

Two new columns are added:
- Total Sales
- Growth Rate

In [25]:
df['Total Sales'] = df.sum(axis=1)

print(df)

     Electronics  Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan       4472.1   3216.40            4390    4796  34813.500000          NaN
Feb       3819.6   3559.80            1590    1711  22378.804984   -34.595016
Mar       2812.5   3627.80            4711    4697  32692.494409    43.194409
Apr       2205.9   2930.80            4771    2994  26547.028492   -18.671508
May       4236.3   2593.35            1095    1889  20534.265340   -21.384660
Jun       3802.5   3291.20            1818    4204  27266.137349    31.437349
Jul       2178.9   1673.65            4972    2620  23411.414367   -15.135633
Aug       2603.7   4222.80            4025    2353  27462.336588    18.836588
Sep       3938.4   2134.35            2731    1241  20880.012378   -23.737622
Oct       2514.6   3444.20            1740    3831  23961.147546    14.347546
Nov       3106.8   1298.80            3077    4735  25012.620053     3.020053
Dec       2591.1   3547.90            4794    3620  30040.911507

In [26]:
df['Growth Rate'] = df['Total Sales'].pct_change() * 100

print(df)

     Electronics  Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan       4472.1   3216.40            4390    4796  34813.500000          NaN
Feb       3819.6   3559.80            1590    1711  22378.804984   -35.718026
Mar       2812.5   3627.80            4711    4697  32692.494409    46.086864
Apr       2205.9   2930.80            4771    2994  26547.028492   -18.797788
May       4236.3   2593.35            1095    1889  20534.265340   -22.649477
Jun       3802.5   3291.20            1818    4204  27266.137349    32.783603
Jul       2178.9   1673.65            4972    2620  23411.414367   -14.137400
Aug       2603.7   4222.80            4025    2353  27462.336588    17.303193
Sep       3938.4   2134.35            2731    1241  20880.012378   -23.968551
Oct       2514.6   3444.20            1740    3831  23961.147546    14.756386
Nov       3106.8   1298.80            3077    4735  25012.620053     4.388239
Dec       2591.1   3547.90            4794    3620  30040.911507

## Step 5: Apply Randomized Discount

Discount is applied based on roll number:
- Even roll number → 10% discount on Electronics
- Odd roll number → 15% discount on Clothing

In [27]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    51688.000000
Feb    33023.486957
Mar    48586.881273
Apr    39429.930704
May    30325.265862
Jun    40414.620952
Jul    34841.826967
Aug    40684.139781
Sep    30900.793827
Oct    35505.703932
Nov    37234.608293
Dec    44614.014525
dtype: float64


In [28]:
df['Clothing'] = df['Clothing'] * 0.85

print(df)

     Electronics   Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan       4472.1  2733.9400            4390    4796  34813.500000          NaN
Feb       3819.6  3025.8300            1590    1711  22378.804984   -35.718026
Mar       2812.5  3083.6300            4711    4697  32692.494409    46.086864
Apr       2205.9  2491.1800            4771    2994  26547.028492   -18.797788
May       4236.3  2204.3475            1095    1889  20534.265340   -22.649477
Jun       3802.5  2797.5200            1818    4204  27266.137349    32.783603
Jul       2178.9  1422.6025            4972    2620  23411.414367   -14.137400
Aug       2603.7  3589.3800            4025    2353  27462.336588    17.303193
Sep       3938.4  1814.1975            2731    1241  20880.012378   -23.968551
Oct       2514.6  2927.5700            1740    3831  23961.147546    14.756386
Nov       3106.8  1103.9800            3077    4735  25012.620053     4.388239
Dec       2591.1  3015.7150            4794    3620 

In [29]:
df['Electronics'] = df['Electronics'] * 0.90

print(df)

     Electronics   Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan      4024.89  2733.9400            4390    4796  34813.500000          NaN
Feb      3437.64  3025.8300            1590    1711  22378.804984   -35.718026
Mar      2531.25  3083.6300            4711    4697  32692.494409    46.086864
Apr      1985.31  2491.1800            4771    2994  26547.028492   -18.797788
May      3812.67  2204.3475            1095    1889  20534.265340   -22.649477
Jun      3422.25  2797.5200            1818    4204  27266.137349    32.783603
Jul      1961.01  1422.6025            4972    2620  23411.414367   -14.137400
Aug      2343.33  3589.3800            4025    2353  27462.336588    17.303193
Sep      3544.56  1814.1975            2731    1241  20880.012378   -23.968551
Oct      2263.14  2927.5700            1740    3831  23961.147546    14.756386
Nov      2796.12  1103.9800            3077    4735  25012.620053     4.388239
Dec      2331.99  3015.7150            4794    3620 

# Part I: Randomized Sales Data Generation

This section generates random monthly sales data using NumPy and converts it into a Pandas DataFrame.

## Step 1: Initialize Random Seed

The roll number is used as a random seed so that each student gets unique sales data.

In [30]:
np.random.seed(902503045)

## Step 2: Generate Sales Data

Random sales data is generated for 12 months and 4 product categories:
- Electronics
- Clothing
- Home & Kitchen
- Sports

Sales values range between 1000 and 5000 units.

In [31]:
sales_data = np.random.randint(1000, 5001, size=(12,4))

print(sales_data)

[[4969 3784 4390 4796]
 [4244 4188 1590 1711]
 [3125 4268 4711 4697]
 [2451 3448 4771 2994]
 [4707 3051 1095 1889]
 [4225 3872 1818 4204]
 [2421 1969 4972 2620]
 [2893 4968 4025 2353]
 [4376 2511 2731 1241]
 [2794 4052 1740 3831]
 [3452 1528 3077 4735]
 [2879 4174 4794 3620]]


In [32]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

## Step 3: Convert NumPy Array into Pandas DataFrame

The generated sales data is converted into a Pandas DataFrame using month names as index labels and product categories as column names.